# Generated by Django 4.2.6 on 2023-12-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('useranme', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('note', models.CharField(max_length=255)),
            ],
        ),
    ]
