# Generated by Django 4.2.6 on 2023-12-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='useranme',
            new_name='username',
        ),
    ]
