# Generated by Django 4.2.6 on 2023-12-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0003_alter_password_code_alter_password_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
